### ISSUE TITLE
Dependency OS version support mismatch using Swift Package Manager

### ISSUE THREAD

**Issue by alexlaurinmath** [googleapis/google-auth-library-swift#38]
The latest version of CryptoSwift only supports versions above 
```
platforms: [
    .macOS(.v10_12), .iOS(.v9), .tvOS(.v9)
  ],
```
<img width="785" alt="Screen Shot 2020-09-18 at 3 29 25 PM" src="https://user-images.githubusercontent.com/16192947/93646589-bf33bf80-f9c3-11ea-9623-eb0beed69bbb.png">

The solution would either be to pin CryptoSwift to versions strictly below 1.3.2, or support the same minimum OS versions.

**Comment by alexlauringoogle** [comment]
I have a PR ready for this. I tried pushing it using my personal and google accounts, but it seems that I don't have the permission. I couldn't find anything in the Contributing doc that shows me what to do.

**Comment by alexlauringoogle** [comment]
I followed these steps: https://g3doc.corp.google.com/company/teams/opensource/cla/index.md?cl=head#googlers

Still no dice.

**Comment by paulb777** [comment]
@alexlauringoogle Are you able to fork the repo and send a PR to fix?

This issue is also breaking the Firebase CI.

**Comment by alexlauringoogle** [comment]
Good idea. I'll keep trying.

**Comment by alexlaurinmath** [comment]
This also blocks
https://github.com/googleapis/google-api-swift-client
